[package]
name = "aurion_plugin_skeleton"
version = "0.1.0"
edition = "2021"
description = "Skeleton plugin for Aurion demonstrating the WASI interface"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
blake3 = "1.4"