name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install additional tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          cargo install cargo-audit --version 0.20.0 || true
          cargo install cargo-license --version 0.5.2 || true
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin v0.98.0

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test --workspace --verbose

      - name: Build release
        run: cargo build --release --workspace --verbose

      - name: Plugin smoke test (WASI)
        run: |
          cd examples/skeleton-plugin
          # Compile plugin to WASI and run via wasmtime to ensure it produces JSON
          cargo build --release --target wasm32-wasi
          wasmtime target/wasm32-wasi/release/skeleton_plugin.wasm --no-cache

      - name: SBOM generation
        run: |
          # generate software bill of materials for the repository
          syft packages dir:. -o cyclonedx-json=sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json
